subscribers:

  camera_info:
    topic: /camera/rgb/camera_info
    queue_size: 1

  camera_reading:
    topic: /camera/rgb/image_raw
    queue_size: 1

  camera_depth_reading:
    topic: /camera/depth_registered/image_raw
    queue_size: 1

actions:

  camera_reading:
    name: /darknet_ros/check_for_objects

services:

  camera_reading:
    name: /darknet_ros/detect_objects

  camera_reading_3d:
    name: /darknet_ros/detect_objects_3d

publishers:

  object_detector:
    topic: /darknet_ros/found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /darknet_ros/bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /darknet_ros/detection_image
    queue_size: 1
    latch: true

  debug_image_output:
    topic: /darknet_ros/debug_image

image_view:

  enable_opencv: true
  wait_key_delay: 1
  enable_console_output: true

image_transport: compressed
